let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Super Lite Salt",
    price: 26,
    desc: "Tata Salt, 1 kg",
    img: "images/salt.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Sulphur Free Sugar",
    price: 43,
    desc: "Pure Sugar 1 Kg",
    img: "images/sugar.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Tomato Ketchup",
    price: 110,
    desc: "Kissan, 500 gm",
    img: "images/ketchup.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Sprite",
    price: 85,
    desc: "Sprite, 2 L",
    img: "images/sprite.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Harpic Power Plus",
    price: 97,
    desc: "Toilet Cleaner, 500 ml",
    img: "images/harpic.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Truke Buds Q1",
    price: 1199,
    desc: "60 Hours Playtime",
    img: "images/buds.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Infinix Y1",
    price: 8999,
    desc: "32inch Frameless HD",
    img: "images/tv.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "POCO M4 Pro",
    price: 11949,
    desc: "6 GB RAM and 128 GB",
    img: "images/mob.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Natural Face Wash",
    price: 216,
    desc: "Face Wash 180 ml",
    img: "images/face.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Aristocrat Polyester",
    price: 2278,
    desc: "78 cms Soft Trolley Bag",
    img: "images/trolley.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "boAt Headphones",
    price: 1500,
    desc: "Wireless Bluetooth Headset",
    img: "images/boat.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Wired USB Mouse",
    price: 269,
    desc: "HP Wired USB Mouse",
    img: "images/mouse.jpg",
  },
  {
    id: "snsnsnsnsnsnsnsnsns",
    name: "Zebronics Keyboard",
    price: 399,
    desc: "Keyboard with USB Input",
    img: "images/key.jpg",
  },
  {
    id: "nmjkloinujlkujnhkoln",
    name: "Nokia 150",
    price: 2599,
    desc: "Keypad mobile",
    img: "images/keypad.jpg",
  },
  {
    id: "qsmddmmopnmkujlkijn",
    name: "Nokia 105",
    price: 1795,
    desc: "Keypad phone",
    img: "images/keymob.jpg",
  },
  {
    id: "xyztytgggytyytbvncv",
    name: "Advanced Python",
    price: 2619,
    desc: "Python Programming Book",
    img: "images/pyth.jpg",
  },
  {
    id: "poytytuyuytyytbvqlb",
    name: "Advance Smartwatch",
    price: 2799,
    desc: "Smartwatch with Alexa",
    img: "images/watch.jpg",
  },{
    id: "ppytytuyuytyytbvncv",
    name: "Travell Sling Bag",
    price: 269,
    desc: "Pure Leather Bag",
    img: "images/bag.jpg",
  },{
    id: "mmmtytuyuytyytbvncv",
    name: "HP Printer Ink",
    price: 735,
    desc: "HP 680 Original Ink",
    img: "images/ink.jpg",
  },{
    id: "mnopytuyuytyytbvncv",
    name: "Leather Wallet(WH2052)",
    price: 239,
    desc: "Pure Leather Waterproof",
    img: "images/wallet.jpg",
  },
];
